[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:cron]
command=cron -f
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/cron.err.log
stdout_logfile=/var/log/supervisor/cron.out.log

[program:artisan-schedule]
command=php /var/www/html/artisan schedule:work
directory=/var/www/html
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/schedule.err.log
stdout_logfile=/var/log/supervisor/schedule.out.log
